{{- if .Values.formalAPIKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-discovery-satellite.fullname" . }}
  labels:
    {{- include "data-discovery-satellite.labels" . | nindent 4 }}
type: Opaque
data:
  formal-api-key: {{ .Values.formalAPIKey | b64enc }}
{{- end }}
