{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-discovery-satellite.serviceAccountName" . }}
  labels:
    {{- include "data-discovery-satellite.labels" . | nindent 4 }}
{{- end }}
