apiVersion: v2
name: kubernetes-operator
description: The Formal Kubernetes Operator automatically registers in-cluster services as Formal resources with fully working connection paths.
type: application
version: 0.2.0
