apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["joinformal.com"]
  resources:
    - formalresources
    - formalresources/status
    - formallisteners
    - formallisteners/status
    - formalnativeusers
    - formalnativeusers/status
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
