{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ai-satellite.fullname" . }}
  labels:
    {{- include "ai-satellite.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ai-satellite.fullname" . }}
  labels:
    {{- include "ai-satellite.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ai-satellite.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ai-satellite.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
