{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-satellite.serviceAccountName" . }}
  labels:
    {{- include "ai-satellite.labels" . | nindent 4 }}
{{- end }}
