apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-satellite.fullname" . }}
  labels:
    {{- include "ai-satellite.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50055
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "ai-satellite.selectorLabels" . | nindent 4 }}
